-- Fixture seeding removed.
-- Canonical editorial content now lives in
-- supabase/migrations/20260812000000_canonical_seed.sql so every environment
-- (local and hosted) receives the same verified, active rows.
