// Generated by manage-cloudflare-preview. Project-owned after creation.

const previewConfig = {
  workerName: "elsi-main-preview",
  candidateAlias: "candidate",
  initialSmokeAttempts: 30,
  packageManager: "pnpm",
  buildEnvironment: {
    NEXT_PUBLIC_PROTOTYPE_MODE: "1",
    NEXT_PUBLIC_CONTENT_STATUS: "fixture",
    NEXT_PUBLIC_SECTION_LABELS: "0",
  },
  healthChecks: [
    {
      path: "/",
      status: 200,
      bodyIncludes: "Conocimiento ambiental para aprender, decidir y actuar.",
    },
    {
      path: "/api/auth/session",
      status: 200,
      jsonEquals: { user: null },
    },
    {
      path: "/robots.txt",
      status: 200,
      bodyIncludes: "Disallow: /",
    },
    {
      path: "/_next/image?url=%2Fhero-bg.jpg&w=640&q=75",
      status: 200,
    },
  ],
};

export default previewConfig;
