// Generated by manage-cloudflare-preview.

import { isDeepStrictEqual } from "node:util";
import { appendFile, readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const apiOrigin = "https://api.cloudflare.com/client/v4";

function requireValue(environment, name) {
  const value = environment[name]?.trim();
  if (!value) throw new Error(`${name} is not configured`);
  return value;
}

export function validateConfig(config) {
  if (!config || typeof config !== "object") throw new Error("Preview config must export an object");
  if (!/^[a-z][a-z0-9-]{0,51}$/.test(config.workerName || "")) {
    throw new Error("workerName must be a lowercase DNS label at most 52 characters long");
  }
  if (!/^[a-z][a-z0-9-]{0,20}$/.test(config.candidateAlias || "")) {
    throw new Error("candidateAlias must be a lowercase DNS label at most 21 characters long");
  }
  if (!["pnpm", "npm"].includes(config.packageManager)) {
    throw new Error("packageManager must be pnpm or npm");
  }
  if (!config.buildEnvironment || typeof config.buildEnvironment !== "object" ||
      Array.isArray(config.buildEnvironment)) {
    throw new Error("buildEnvironment must be an object");
  }
  for (const [name, value] of Object.entries(config.buildEnvironment)) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(name) || typeof value !== "string") {
      throw new Error(`Invalid public build environment entry: ${name}`);
    }
    if (!name.startsWith("NEXT_PUBLIC_") && name !== "NEXTJS_ENV") {
      throw new Error(`Only NEXT_PUBLIC_* and NEXTJS_ENV may be stored in buildEnvironment: ${name}`);
    }
  }
  if (!Array.isArray(config.healthChecks) || config.healthChecks.length === 0) {
    throw new Error("healthChecks must contain at least one check");
  }
  for (const check of config.healthChecks) {
    if (!check || typeof check !== "object" || typeof check.path !== "string" ||
        !check.path.startsWith("/") || check.path.startsWith("//")) {
      throw new Error("Every health check path must begin with one slash");
    }
    if (!Number.isInteger(check.status) || check.status < 100 || check.status > 599) {
      throw new Error(`Invalid health check status for ${check.path}`);
    }
    if ("bodyIncludes" in check && typeof check.bodyIncludes !== "string") {
      throw new Error(`bodyIncludes must be a string for ${check.path}`);
    }
  }
  return config;
}

function defaultRun(command, args, options = {}) {
  const capture = options.capture === true;
  const result = spawnSync(command, args, {
    cwd: options.cwd,
    env: options.env,
    encoding: "utf8",
    stdio: capture ? ["ignore", "pipe", "pipe"] : "inherit",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    const detail = capture ? `: ${(result.stderr || result.stdout || "").trim()}` : "";
    throw new Error(`${command} ${args.join(" ")} failed with exit ${result.status}${detail}`);
  }
  return { stdout: result.stdout || "", stderr: result.stderr || "" };
}

function executable(config, name, args) {
  return config.packageManager === "pnpm"
    ? ["pnpm", ["exec", name, ...args]]
    : ["npx", ["--no-install", name, ...args]];
}

function runExecutable(run, config, name, args, options) {
  const [command, commandArgs] = executable(config, name, args);
  return run(command, commandArgs, options);
}

async function defaultApiRequest({ accountId, token, path, allowNotFound = false }, fetchImpl) {
  const response = await fetchImpl(`${apiOrigin}${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
  });
  const payload = await response.json().catch(() => null);
  if (allowNotFound && response.status === 404) return null;
  if (!response.ok || payload?.success !== true) {
    const messages = [...(payload?.errors || []), ...(payload?.messages || [])]
      .map((item) => item?.message)
      .filter(Boolean)
      .join("; ");
    throw new Error(`Cloudflare API ${response.status}${messages ? `: ${messages}` : ""}`);
  }
  return payload.result;
}

export function activeVersionFromDeployments(result) {
  if (result === null) return null;
  const deployments = result?.deployments;
  if (!Array.isArray(deployments)) throw new Error("Cloudflare deployments response is malformed");
  if (deployments.length === 0) return null;
  const versions = deployments[0]?.versions;
  if (!Array.isArray(versions) || versions.length !== 1 ||
      Number(versions[0].percentage) !== 100 || !versions[0].version_id) {
    throw new Error("Preview Worker must have one active version at 100 percent");
  }
  return versions[0].version_id;
}

function versionIds(value) {
  const versions = Array.isArray(value) ? value : value?.versions;
  if (!Array.isArray(versions)) throw new Error("Wrangler versions output is malformed");
  return new Set(versions.map((version) => version.id).filter(Boolean));
}

async function readVersions({ run, config, cwd, environment }) {
  const result = runExecutable(
    run,
    config,
    "wrangler",
    ["versions", "list", "--name", config.workerName, "--json"],
    { cwd, env: environment, capture: true },
  );
  try {
    return versionIds(JSON.parse(result.stdout));
  } catch (error) {
    throw new Error(`Unable to parse Wrangler versions JSON: ${error.message}`, { cause: error });
  }
}

async function fetchWithTimeout(fetchImpl, url, timeoutMilliseconds) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMilliseconds);
  try {
    return await fetchImpl(url, {
      redirect: "follow",
      signal: controller.signal,
      headers: { "User-Agent": "zivelo-cloudflare-preview-smoke/1" },
    });
  } finally {
    clearTimeout(timer);
  }
}

async function checkOnce(fetchImpl, baseUrl, check) {
  const url = new URL(check.path, `${baseUrl}/`).href;
  const response = await fetchWithTimeout(fetchImpl, url, 10_000);
  const body = await response.text();
  if (response.status !== check.status) {
    throw new Error(`${check.path} returned ${response.status}, expected ${check.status}`);
  }
  if (check.bodyIncludes !== undefined && !body.includes(check.bodyIncludes)) {
    throw new Error(`${check.path} did not include required text`);
  }
  if (check.jsonEquals !== undefined) {
    let parsed;
    try {
      parsed = JSON.parse(body);
    } catch {
      throw new Error(`${check.path} did not return valid JSON`);
    }
    if (!isDeepStrictEqual(parsed, check.jsonEquals)) {
      throw new Error(`${check.path} returned unexpected JSON`);
    }
  }
}

export async function smokeChecks(fetchImpl, baseUrl, checks, dependencies = {}) {
  const wait = dependencies.wait || ((milliseconds) =>
    new Promise((resolveWait) => setTimeout(resolveWait, milliseconds)));
  const attempts = dependencies.attempts || 10;
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      for (const check of checks) await checkOnce(fetchImpl, baseUrl, check);
      return;
    } catch (error) {
      lastError = error;
      if (attempt < attempts) await wait(2_000);
    }
  }
  throw new Error(`Smoke checks failed for ${baseUrl}: ${lastError.message}`, { cause: lastError });
}

async function writeOutputs(environment, values) {
  if (!environment.GITHUB_OUTPUT) return;
  const lines = Object.entries(values).map(([name, value]) => `${name}=${value}`).join("\n");
  await appendFile(environment.GITHUB_OUTPUT, `${lines}\n`, "utf8");
}

export async function deployPreview(options = {}, dependencies = {}) {
  const cwd = resolve(options.cwd || process.cwd());
  const environment = dependencies.environment || process.env;
  const run = dependencies.run || defaultRun;
  const fetchImpl = dependencies.fetch || fetch;
  const log = dependencies.log || console.log;
  const accountId = requireValue(environment, "CLOUDFLARE_ACCOUNT_ID");
  const token = requireValue(environment, "CLOUDFLARE_API_TOKEN");
  const sourceRevision = requireValue(environment, "SOURCE_REVISION");
  if (!/^[0-9a-f]{40}$/i.test(sourceRevision)) {
    throw new Error("SOURCE_REVISION must be a full Git commit SHA");
  }

  const configPath = resolve(cwd, ".zivelo", "cloudflare-preview.config.mjs");
  const config = validateConfig(
    options.config ||
    (await import(`${pathToFileURL(configPath).href}?revision=${Date.now()}`)).default,
  );
  const apiRequest = (path, requestOptions = {}) => defaultApiRequest({
    accountId,
    token,
    path,
    ...requestOptions,
  }, fetchImpl);
  const accountPath = `/accounts/${encodeURIComponent(accountId)}`;
  const workerPath = `${accountPath}/workers/scripts/${encodeURIComponent(config.workerName)}`;

  const subdomainResult = await apiRequest(`${accountPath}/workers/subdomain`);
  const subdomain = subdomainResult?.subdomain;
  if (!subdomain) throw new Error("The Cloudflare account has no Workers subdomain");
  const stableUrl = `https://${config.workerName}.${subdomain}.workers.dev`;
  const candidateUrl =
    `https://${config.candidateAlias}-${config.workerName}.${subdomain}.workers.dev`;
  const safeProcessEnvironment = { ...environment };
  delete safeProcessEnvironment.CLOUDFLARE_ACCOUNT_ID;
  delete safeProcessEnvironment.CLOUDFLARE_API_TOKEN;
  const buildEnvironment = {
    ...safeProcessEnvironment,
    ...config.buildEnvironment,
    NEXT_PUBLIC_SITE_URL: stableUrl,
  };
  const cloudflareEnvironment = {
    ...buildEnvironment,
    CLOUDFLARE_ACCOUNT_ID: accountId,
    CLOUDFLARE_API_TOKEN: token,
  };

  const deploymentBefore = await apiRequest(`${workerPath}/deployments`, {
    allowNotFound: true,
  });
  const previousVersionId = activeVersionFromDeployments(deploymentBefore);
  const versionsBefore = await readVersions({
    run,
    config,
    cwd,
    environment: cloudflareEnvironment,
  }).catch((error) => {
    if (previousVersionId === null && /failed with exit/.test(error.message)) return new Set();
    throw error;
  });

  log(`Building ${config.workerName} for ${sourceRevision}`);
  runExecutable(run, config, "opennextjs-cloudflare", ["build"], {
    cwd,
    env: buildEnvironment,
  });
  runExecutable(run, config, "wrangler", ["deploy", "--dry-run"], {
    cwd,
    env: cloudflareEnvironment,
  });
  runExecutable(
    run,
    config,
    "opennextjs-cloudflare",
    [
      "upload",
      "--preview-alias",
      config.candidateAlias,
      "--message",
      `Preview candidate ${sourceRevision}`,
    ],
    { cwd, env: cloudflareEnvironment },
  );

  const versionsAfter = await readVersions({
    run,
    config,
    cwd,
    environment: cloudflareEnvironment,
  });
  const newVersionIds = [...versionsAfter].filter((id) => !versionsBefore.has(id));
  if (newVersionIds.length !== 1) {
    throw new Error(`Expected exactly one new Worker version, found ${newVersionIds.length}`);
  }
  const newVersionId = newVersionIds[0];

  log(`Smoke-testing candidate ${newVersionId}`);
  await smokeChecks(fetchImpl, candidateUrl, config.healthChecks, dependencies);
  runExecutable(
    run,
    config,
    "wrangler",
    [
      "versions",
      "deploy",
      `${newVersionId}@100%`,
      "--yes",
      "--message",
      `Promote ${sourceRevision}`,
    ],
    { cwd, env: cloudflareEnvironment },
  );

  try {
    await smokeChecks(fetchImpl, stableUrl, config.healthChecks, dependencies);
    const deploymentAfter = await apiRequest(`${workerPath}/deployments`);
    const activeVersionId = activeVersionFromDeployments(deploymentAfter);
    if (activeVersionId !== newVersionId) {
      throw new Error(`Stable deployment is ${activeVersionId}, expected ${newVersionId}`);
    }
  } catch (deploymentError) {
    if (!previousVersionId) {
      throw new Error(
        `Stable verification failed on the first deployment; no rollback version exists: ${deploymentError.message}`,
        { cause: deploymentError },
      );
    }
    log(`Stable verification failed; restoring ${previousVersionId}`);
    try {
      runExecutable(
        run,
        config,
        "wrangler",
        [
          "versions",
          "deploy",
          `${previousVersionId}@100%`,
          "--yes",
          "--message",
          `Automatic rollback after ${sourceRevision}`,
        ],
        { cwd, env: cloudflareEnvironment },
      );
      await smokeChecks(fetchImpl, stableUrl, config.healthChecks, dependencies);
    } catch (rollbackError) {
      throw new Error(
        `Stable verification failed and rollback also failed: ${deploymentError.message}; rollback: ${rollbackError.message}`,
        { cause: rollbackError },
      );
    }
    throw new Error(
      `Stable verification failed; restored ${previousVersionId}: ${deploymentError.message}`,
      { cause: deploymentError },
    );
  }

  await writeOutputs(environment, {
    preview_url: stableUrl,
    worker_version_id: newVersionId,
    source_revision: sourceRevision,
  });
  log(`Deployed ${sourceRevision} as ${newVersionId} to ${stableUrl}`);
  return { stableUrl, candidateUrl, newVersionId, previousVersionId, sourceRevision };
}

const isEntrypoint = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isEntrypoint) {
  deployPreview().catch((error) => {
    console.error(`Cloudflare preview deployment failed: ${error.message}`);
    process.exitCode = 1;
  });
}
